### ISSUE TITLE
All notes not updating

### ISSUE THREAD

**Issue by stevenwcarter** [dsebastien/obsidian-dataview-serializer#27]
I was happy to see this plugin, since this has been a pain point for me in the past.

Upon trying out your plugin, I was surprised to see that queries in unmodified files weren't being updated. I pulled down the code and discovered that this plugin only updates files if the file itself hash been recently updated. Additionally, the logic to confirm that a file has not been updated too recently is using the file's mtime. The file mtime will always be prior to the current timestamp + 5 seconds unless a user goes to the file and modifies it. This doesn't work well for files that should have their queries updated as the result of a _different_ file changing. 

I'm working on a PR, but there are some problems with the build so it might take a little before I figure out the issues with `nx` to get the build running properly. I'm at least able to use my updates in the meantime, so I just wanted to contribute back so others could enjoy the update as well.

**Comment by dsebastien** [comment]
Hi Steven,

Thanks for chiming in!
I initially made this design decision because I didn't want older daily notes to be touched/modified by this plugin. But I agree that it actually makes more sense to update all matching queries as soon as possible.

Your proposal will help keep things up to date where needed; I like it.

Glad you could work around the issues with Nx. Which ones did you face BTW? Issues with the cloud token? I need to improve the plugin template to include a test vault; the current dev logic doesn't work.

🚀

**Comment by dsebastien** [comment]
Releasing 1.5.0 with the changes! 🎉

**Comment by stevenwcarter** [comment]
I wrote a Rust program to update all my notes to transition from dataview, and noticed that there are some performance problems with this change when you have a lot of notes that have the queries, but aren't routinely updated. I'll provide a PR shortly with a new change. I've added a new configuration value that allows users to detail which folders they want to always be updated with any file changes. The command palette functionality is unchanged, so it will still update all of the searches, same as before.

The issue I was having with `nx` was the `npm run lint` command was failing for me. I didn't look too closely at the stack trace, but it certainly looked cryptic.
