### ISSUE TITLE
The "Scan and serialize all Dataview queries" command is broken

### ISSUE THREAD

**Issue by tijmenvdk** [dsebastien/obsidian-dataview-serializer#7]
Currently, only the folders that are explicitly listed in the settings file are scanned and updated, but I would like/need the option to redo all dataviews in the vault on demand.

**Comment by dsebastien** [comment]
Hello,

I did not test it, but I assume you could add / as a folder to scan to include everything. Then, you should be able to invoke the 'Scan and serialize all Dataview queries' command to scan everything except the excluded folders.

**Comment by dsebastien** [comment]
I just tested this and it works fine. I'll close this as there is a solution to achieve what you want.

**Comment by tijmenvdk** [comment]
Thanks for looking into this. I have tested this further. What I did:

1. create an index page that lists a specific frontmatter attribute from a number of files, and close that (in Obsidian)
2. change the frontmatter attibute in one of the listed pages
3. ctrl+P and "scan and serialize all dataview queries"
4. watch the listed page in Notepadd++ for changes

What I observed:

- changes are only picked up after turning the plugin off and on, otherwise the "scan and serialize" task has no effect.
- adding `/` does not work in my case; changes never get picked up.
- adding the root folders in my vault does work, and changes in underlying files are picked up (taking bullet 1 into account)

So, this works:

![image](https://github.com/dsebastien/obsidian-dataview-serializer/assets/85442373/05c64a5d-52b3-4289-849d-03a39d045620)

It works like this, the only annoyance is that I have to turn the plugin off and on to get things to work.

**Comment by dsebastien** [comment]
I just noticed a bug in the command that might explain the behavior you noticed. The command is indeed broken, and doesn't process anything. The command itself filters out files that should be processed, and asks for processing files that are ignored. Then, the function that is supposed to process the files ignores those because they are of course in the ignore list. Thus nothing happens.

https://github.com/dsebastien/obsidian-dataview-serializer/blob/master/apps/plugin/src/app/plugin.ts#L100

It's an easy fix though, I'll take care of it soon
