### ISSUE TITLE
Some form of manual control over table format

### ISSUE THREAD

**Issue by Accelsnow** [dsebastien/obsidian-dataview-serializer#8]
Just want to first say thanks! This plugin is an absolute game changer in site-publishing (I use Quartz and it works like a charm)! 

One suggestion (or nice-to-have) is that currently there is no control over how the table columns are formatted (more specifically, column width). I see an open ticket regarding minimizing spacing #1 . I want to add that it would be nice to have some form of manual control over the column width. Say I have a table with a list column, a name text column, an image column and a URL text column. I may want the name text column and list column to fit as much as possible and images to fit to a specific width. I wouldn't mind the URL columns to be wrapped so they can have a short width. Currently it seems like it's allocating too much space for URL because of its length, and the images fit differently.

I am not an expert of obsidian plugins or dataview, but maybe this can be achieved through CSS classes/ids or some hardcoded config alongside with the query itself.

Thanks again for the great plugin!

**Comment by dsebastien** [comment]
Hello @Accelsnow. You're welcome.
Great to know that it works with Quartz as well. I didn't test it, but it makes sense as this is just generating Markdown :)

I don't have control over the generated Markdown code. This plugin only acts as a bridge to the Dataview plugin. The Dataview plugin is the one performing the transformation from query to results, then from results to Markdown.

I'll close this issue for now, because I won't be able to help without investing a lot of time into duplicating/changing the behavior of Dataview. Sorry to disappoint!
